version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - "5000:5000"

  stock:
    build: ./stock-service
    ports:
      - "5001:5001"

  panier:
    build: ./panier-service
    ports:
      - "5002:5002"

  transaction:
    build: ./transaction-service
    ports:
      - "5003:5003"

  historique:
    build: ./historique-service
    ports:
      - "5004:5004"
